name: projective_orchestration
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - pretty_midi
  - pytorch
  - torchvision
  - torchaudio
  - pip

  # HTTP backend for interactive exploration
  - fastapi
  - uvicorn
  - python-multipart

# to set up:
# conda env create -f environment.yml
# conda activate projective_orchestration